name: 'Deploy SAM GitHub Actions'
branding:
  icon: 'terminal'
  color: 'orange'
runs:
  using: 'composite'
  steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Setup AWS CLI
      run: pip install awscli
      shell: bash

    - name: Setup AWS SAM CLI
      run: pip install aws-sam-cli
      shell: bash

    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: .

    - name: Uncompress Artifact
      run: |
        tar -xzvf dist.tar.gz
      shell: bash

    - name: Deploy AWS SAM
      run: |
        sam deploy --template-file dist/template.yaml --config-env ${{ github.ref_name }} --no-fail-on-empty-changeset  
      shell: bash
